### ISSUE TITLE
Bug: Memory

### ISSUE THREAD

**Issue by fluffeliger** [FrozenAssassine/WS2812-Controller#1]
Im not entirely sure but i think i spotted a mistake. At line 105 in WS2812.h
```c++
leditems = (LedItem*)malloc(nbrOfPixels);
```
doesnt allocate the whole object. Maybe change it to this? or correct me if im wrong:
```c++
leditems = (LedItem*)malloc(nbrOfPixels*sizeof(LedItem));
```

**Comment by FrozenAssassine** [comment]
Yeah you are totally correct, I really missed that. I will fix this, thank you very much
